name: Equipper
main: com.plugkin.equipper.Equipper
version: 0.1
author: Zivci

commands:
   equip:
      description: This command equips entity with given armour item.
      usage: /<command> [player]
      permission: equipper.use
      permission-message: "ยง4Error: No permission."